name = "thyroxeia"

main = "worker-clean.js"

compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

account_id = "3c8e6479a51ea2c61bffd9386a3b80d7"





[assets]

directory = "./public_fixed3"
